### ISSUE TITLE
Error Calculating ROC

### ISSUE THREAD

**Issue by aunsid** [Abe404/segmentation_of_roots_in_soil_with_unet#1]
I used your metrics.py file to plot the roc curve but it does not give the required output. Are the calculations for TP, FP , TN and FN calculated aptly? 
The plot that I got wasnt of a scale from 0 to 1 for both TPR and FPR.

**Comment by Abe404** [comment]
Hi Mohammed,

Where are you getting FPR from?

We compute tp, tn, fp, and fn assuming both predicted and ground truth values are all 0 or 1.

From: https://github.com/Abe404/segmentation_of_roots_in_soil_with_unet/blob/master/src/metrics.py#L40
true_positives = np.sum(np.logical_and(y_pred == 1, y_true == 1))
true_negatives = np.sum(np.logical_and(y_pred == 0, y_true == 0))
false_positives = np.sum(np.logical_and(y_pred == 1, y_true == 0))
false_negatives = np.sum(np.logical_and(y_pred == 0, y_true == 1))

Then we compute precision and recall from these.

From https://github.com/Abe404/segmentation_of_roots_in_soil_with_unet/blob/master/src/metrics.py#L51
precision = true_positives / (true_positives + false_positives)
recall = true_positives / (true_positives + false_negatives)

From wikipedia [0]
recall = TPR = tp/(tp+fn)
precision = tp/(tp+fp)
TNR = tn/(tn+fp)


Perhaps what we calculate is correct but difference between TNR and precision could explain your results?

[0] https://en.wikipedia.org/wiki/Sensitivity_and_specificity

**Comment by aunsid** [comment]
I compared the same unet using your metric.py vs the implementation from this [blog]( https://medium.com/kitepython/image-segmentation-with-python-213b3b016e7d)
![segment-root](https://user-images.githubusercontent.com/34586854/92616680-880b3300-f28c-11ea-8687-02f853cb65b2.png)
![kite-root](https://user-images.githubusercontent.com/34586854/92616689-8b062380-f28c-11ea-9255-09c30aed2a70.png)

I don't know which implementation is correct. But the results are different.

**Comment by Abe404** [comment]
Thanks for the extra detail. It's a bit hard for me to debug as this code requires the rest of your system to run.

Could you create a test case that isolates the problem a bit more? Perhaps a single python file that I could run which shows how the two functions give different output for the same input? 

Another idea to help identify the problem would be to call np.unique on both the inputs to get_metrics i.e true and predicted. They should include either 0,1 or both.

Also why are you computing mean for mean_tp, mean_fp etc. Shouldn't this just be a sum?

**Comment by Abe404** [comment]
Looking again at your metrics output, the predicted mean is in some cases around 20. This indicates the input is not binary. The get metrics function deals with a binary array e.g every value is 0 or 1.

**Comment by aunsid** [comment]
Good catch with the np.sum() with np.mean(). 

I thought with np.logical() it just cared for 0 (as 0) and non 0 vals as 1. Cause my annotated mask is binary. 

I did change it. Now it seems that the fp is flipped with fn. 

![segment-root1](https://user-images.githubusercontent.com/34586854/92633664-1984a000-f2a1-11ea-8b1e-db9c5f019bd2.png)
![kite-root1](https://user-images.githubusercontent.com/34586854/92633674-1d182700-f2a1-11ea-80d4-bc8c73d02c77.png)
![segment-root2](https://user-images.githubusercontent.com/34586854/92633686-1f7a8100-f2a1-11ea-81b3-52039367e5b0.png)
![kite-root2](https://user-images.githubusercontent.com/34586854/92633693-21dcdb00-f2a1-11ea-8be6-620ced4dc96c.png)

**Comment by aunsid** [comment]
I cant give you the exact test case cause the weights are large.

I was just using the Unet and weights from [PlantRootSeg](https://github.com/GatorSense/PlantRootSeg)  Same as idea as your paper.
 But they dont have code for eval metrics that why I was using yours.

**Comment by Abe404** [comment]
I don't need weights. Just an example showing how the behaviour is different. You could could use just a few numbers e.g a short manually defined array in order to compare the functionality of get_metrics and the other function.

e.g
predicted = [1,1,0,0]
true = [1,1,1,0]
Then use these example arrays to show how get_metrics is not correct etc (or your other function)

Did you try with np.unique to check your inputs are all 0 and 1?

Do you still think there could be a problem with my get_metrics function? It seems to me from the example images that you might have mixed up the true and predicted in your input to the other function? If you switch them around it should all align nicely.

**Comment by aunsid** [comment]
torch.unique(true_masks)
tensor([0, 1], dtype=torch.int32)

I did check unique. 

Ya, the mistake was y_pred and y_true. **Both functions had it interchanged**. And I didnt check that. 


Thanks for all the help!

**Comment by Abe404** [comment]
I'm am happy I could help :) if my work has been useful for you please star the repo and cite the paper.

Good luck with your project!
